#! /bin/python3
import sys
from pytubefix import YouTube

def main():
    # process arguments and environment variables
    if len(sys.argv) != 2:
        print(f"Usage: {sys.argv[0]} [video ID]")
        return

    video_id = sys.argv[1]
    yt = YouTube(f"https://youtu.be/{video_id}")

    video_title = yt.title
    video_desc = yt.description
    video_desc_lines = video_desc.split("\n")

    # try to parse videos that are auto-generated by youtube (common format)
    auto_generated = "Auto-generated by YouTube." in video_desc_lines

    if auto_generated:
        # title + artists & album will always be on the same line number
        title_artists = video_desc_lines[2].split("·")
        title = title_artists[0]
        artists = list(map(lambda x: x.strip(), title_artists[1:]))
        album = video_desc_lines[4]

        # trying to extract release year is a little more difficult, may have
        # to rely on copyright year
        year = None
        for line in video_desc_lines:
            if "Released on: " in line:
                release_date = line.split(" ")[2]
                year = release_date.split("-")[0]
                break

            elif "℗" in line:
                year = line.split(" ")[1]

        print(f"Title: {title}")
        print(f"Artist(s): {artists}")
        print(f"Album: {album}")
        print(f"Year: {year}")

        return

    # use audio fingerprinting to identify song
    # yt.streams.get_audio_only().download()

if __name__ == "__main__":
    main()
